### PR TITLE
docs: Configure keycloak 18 dns resolution

### PR DESCRIPTION
**Pull request by yelhouti**

### CODE REVIEW

**Comment by vishal423** [comment]
@yelhouti. Thanks for your contribution. Since the change applies to the upcoming JHipster version (yet not released), I will put this on hold for now.

**Comment by yelhouti** [comment]
of course thanks

**Comment by vishal423** [comment]
It seems to be not required anymore. Can we close @yelhouti ?

**Comment by yelhouti** [comment]
Indeed yes please go ahead

**Pull request closed without merging**
