### PR TITLE
feat: Support micro-services application generation

### LINKED ISSUE #530: Support micro-services application generation

### PR DESCRIPTION
**Pull request by vishal423**
Closes #530 

---
- Synchronize JHipster templates overridden in the blueprint
- Correct relationships import path in svelte and cypress code
- CI job to verify micro-services application generation

### CODE REVIEW

**Comment by vishal423** [comment]
@mraible, would you be able to review the micro-services support?

**Comment by mraible** [comment]
Yes, I'll try to take a look in a few hours. I'm planning on using the following command to test:

```
jhipster jdl reactive-mf --blueprints svelte --client-framework svelte
```

Hopefully, this will work. You can see the reactive-mf JDL at https://github.com/jhipster/jdl-samples/blob/main/reactive-mf.jdl.

**Comment by mraible** [comment]
I tried the command above and was able to start everything successfully. However, after authenticating in the gateway, I don't see any menu items.

Screen Shot 2022-05-10 at 16 47 23

If I run `npm start` in the gateway, it doesn't help. I tried running it in the blog app too, but it fails there.

```
> blog@0.1.0 start
> svelte-kit dev --port 9000 --open true

Your jsconfig.json should extend the configuration generated by SvelteKit:
{
  "extends": "./.svelte-kit/tsconfig.json"
}
> Port 9000 is already in use
    at Server.onError (/Users/mraible/Downloads/smf/blog/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:47384:28)
    at Server.emit (node:events:527:28)
    at emitErrorNT (node:net:1399:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

If I run `npm run e2e` in the gateway, it works:

```
    ✔  All specs passed!                        01:48       26       26        -        -        -
```

If stop the gateway's `npm start` and run `npm start` in the blog directory, the UI comes up and I'm able to see entities. When I try to create a new blog, it 404s.

Screen Shot 2022-05-10 at 16 59 15

If I run `npm run e2e`, it seems to run tests against the gateway, rather than the blog only.

```
    ✖  17 of 20 failed (85%)                    09:53       79       20       49        -       10
```

I believe @mshima implemented things with the expectation that e2e tests could not be run as a whole (like they can on the gateway with a monolith UI), but you can run them all using `npm run e2e --workspaces`. 

See [my previous comments here](https://github.com/jhipster/generator-jhipster/pull/18103#pullrequestreview-919370929) about testing microfrontends with Cypress.

**Comment by vishal423** [comment]
It doesn't looks correct as `blog` should have been a microservice (no micro-frontend support) without UI. Can you test with local JDL removing `clientFramework` from each microservice application configuration and not passing `client-framework` as cli option

**Comment by mraible** [comment]
@vishal423 As far as I know, adding `clientFramework` to each microservice is the only way to currently trigger microfrontends. Are you using a different technique? 

I tried the JDL below this morning and the results (no entities on gateway) are the same:

```
application {
  config {
    baseName gateway
    reactive true
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2
    buildTool gradle
    clientFramework svelte
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    clientFramework svelte
    databaseType neo4j
    devDatabaseType neo4j
    prodDatabaseType neo4j
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store
    reactive true
    packageName com.okta.developer.store
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    clientFramework svelte
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}
```

If I update this JDL to use `clientFramework: angularX`, and generate it with the main generator, the gateway shows entities, and everything works as expected.

Screen Shot 2022-05-11 at 09 06 44

**Comment by vishal423** [comment]
@mraible , I think there is confusion. Svelte blueprint doesn't yet support micro-frontends. This PR only adds support for Reactive Gateway and micro-service applications. Can you please test if that works for you?

**Comment by mraible** [comment]
I tried with `shipster jdl reactive-ms` and it seems to have worked. I was able to build Docker images and run everything with `docker compose up`. When I first tried to run `npm run e2e` in the gateway app, it fails after a while.

```
Still waiting to connect to Chrome, retrying in 1 second (attempt 62/62)
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 58637.

Error: connect ECONNREFUSED 127.0.0.1:58637
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)

Execution time: 8 min. 33 s.
```

I'll try again.

**Comment by mraible** [comment]
I dig the logo for this blueprint!

Screen Shot 2022-05-11 at 20 58 25

This time, all Cypress tests pass! 💯 

Screen Shot 2022-05-11 at 21 24 34

I can't wait until Cypress run faster on M1.

**Review by mraible — APPROVED** [review]

**Comment by vishal423** [comment]
Thanks for review @mraible 

I see a few posts suggesting building local cypress binary; not sure if that's doable and gain.

**Comment by pascalgrimaud** [comment]
@vishal423 : approved and good job :-)

**Pull request merged**
